### ISSUE TITLE
is it possble to add data file for test like in https://github.com/blazs/HoeffdingTree

### ISSUE THREAD

**Issue by Sandy4321** [vitords/HoeffdingTree#2]
it give error
builtins.FileNotFoundError: [Errno 2] No such file or directory: 'dataset_file.csv'
so it would be nice to have data file and results of classification to make sure it runs corectly 
for example you may use the same data as in 
https://github.com/blazs/HoeffdingTree
housing.dat
housing-100K.dat
sample.dat
sea.dat
winnow.dat

**Comment by vitords** [comment]
You can use any dataset you want. Just use a file in CSV format with a header containing all the attribute names.

If you choose to run the `main.py` example all you need to do is rename your dataset to `dataset_file.csv` or change the name inside the script.
