### ISSUE TITLE
The *distribution_for_instance method* always gives the same class probabilities for each class

### ISSUE THREAD

**Issue by TxusLopez** [vitords/HoeffdingTree#4]
Dear vitords,

I have been using your VFDT (thanks for your great work), and I have found that when I have a new instance and I want to know the predicted class, the method `distribution_for_instance` should provides the class probabilities for this new instance. But, I have found that the class probabilities are always distributed proportionally to the number of values ​​of the class. 

For example: if my class have these values [0,1], the method always gives [0.5,0.5]. If my class have these values [0,1,2], the method always gives [0.33,0.33,0.33], etc.

Do you know what I can be doing wrong?

Thanks in advance.

**Comment by TxusLopez** [comment]
In order to give more information about this issue, my code (training and testing with iris datset) is:

`    new_divtest_instance = Instance(att_values=list(['5.1','3.8','1.9','0.4','Iris-setosa']))
    new_divtest_instance.set_dataset(dataset)
    probs=vfdt.distribution_for_instance(new_divtest_instance)
`
`print (probs)`

Then, I obtain: `[0.3333333333333333, 0.3333333333333333, 0.3333333333333333]`

**Comment by vitords** [comment]
Hello @TxusLopez, it looks like your test is getting to this point: https://github.com/vitords/HoeffdingTree/blob/master/hoeffdingtree.py#L160
For some reason, your tree has no root node. How are you initializing/building the tree updating the classifier up to the point of seeing this distribution?

**Comment by TxusLopez** [comment]
Thanks for your response @vitords, my code is as follows:

```
def main():
    filename = 'dataset_file.csv'
    dataset = open_dataset(filename, 4, probe_instances=10000)
    vfdt = HoeffdingTree()
    
    # Set some of the algorithm parameters
    vfdt.set_grace_period(50)
    vfdt.set_hoeffding_tie_threshold(0.05)
    vfdt.set_split_confidence(0.0001)
    # Split criterion, for now, can only be set on hoeffdingtree.py file.
    # This is only relevant when Information Gain is chosen as the split criterion
    vfdt.set_minimum_fraction_of_weight_info_gain(0.01)

    vfdt.build_classifier(dataset)
    
    # Simulate a data stream
    with open(filename) as f:
        stream = csv.reader(f)
        # Ignore the CSV headers
        next(stream)
        for item in stream:
            inst_values = list(item)
            #print (inst_values)
            for i in range(len(inst_values)):
                if dataset.attribute(index=i).type() == 'Nominal':
                    inst_values[i] = int(dataset.attribute(index=i)
                        .index_of_value(str(inst_values[i])))
                else:
                    inst_values[i] = float(inst_values[i])
            new_instance = Instance(att_values=inst_values)
            new_instance.set_dataset(dataset)
            vfdt.update_classifier(new_instance)
    print(vfdt)

    new_divtest_instance = Instance(att_values=list(['5.1','3.8','1.9','0.4','Iris-setosa']))
    new_divtest_instance.set_dataset(dataset) 

    probs=vfdt.distribution_for_instance(new_divtest_instance)
    print (probs)
    
if __name__ == '__main__':
    main()
```

being the `dataset_file.csv` the classical `iris dataset` like:

```
x1,x2,x3,x4,class
5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
```

**Comment by vitords** [comment]
Hello @TxusLopez, I've run your code and the output of the probabilities was the following:
`[0.32019704433497537, 0.3399014778325123, 0.3399014778325123]`
Are you sure this is the code that's giving you the distribution `[0.3333333333333333, 0.3333333333333333, 0.3333333333333333]`?

**Comment by TxusLopez** [comment]
Hello @vitords,

yes, this is the code, but please find attached the main class and the csv file (both in txt to update them here, please rename them to .py and .csv), just in case ...

Thanks

[dataset_file.txt](https://github.com/vitords/HoeffdingTree/files/950634/dataset_file.txt)
[main.txt](https://github.com/vitords/HoeffdingTree/files/950635/main.txt)

**Comment by vitords** [comment]
Indeed the probability distribution is as you reported. It looks like that's caused by the size of your tree, it's not that it does not have a root, but that the root is its only node, as you can see by the result of `print(vfdt)`.

In fact, the iris dataset only contains 150 instances, which is a really small amount for algorithms intended to be used on data streams, such as Hoeffding Tree. You can see some interesting results by adding some fake data to your code, like in this quick test:
```import random```
...
```
for i in range(1000000):
    new_instance = Instance(att_values=list([random.uniform(0, 6), random.uniform(0, 4), random.uniform(0, 2), random.uniform(0, 0.5), random.randrange(0, 3)]))
    new_instance.set_dataset(dataset)
    vfdt.update_classifier(new_instance)
print(vfdt)
```
Add this right before your `new_divtest_instance = ...`.

Hope this helps.

**Comment by TxusLopez** [comment]
Dear @vitords ,

Effectively, as you suggested, the number of instances was not big enough so as to train the tree in an assumed online learning scenario.

Thanks a lot for your support and great work.

Txus
