### ISSUE TITLE
data set

### ISSUE THREAD

**Issue by AkramMohammadi** [vitords/HoeffdingTree#6]
Hi,sir

I want know, what used data set for train and test, I need use for experiments.
I want to help,what was type data set used code.

Thanks .
Mohammadi

**Comment by vitords** [comment]
See issue #2:

You can use any dataset you want. Just use a file in CSV format with a header containing all the attribute names.
If you choose to run the `main.py` example all you need to do is rename your dataset to `dataset_file.csv` or change the name inside the script.

There's no support for model evaluation in this repository, so you'll just need a train set (either by using a large dataset in CSV format, or setting up your own way to feed a data stream to the algorithm).

**Comment by AkramMohammadi** [comment]
Ok,thanks.
I want improve the algorithm, but  print just print (vfdt)
 just print  :(110001) , have problems with output.
I  used data set Higgs bosson
can not give dimensions "len(post_dist)" and "len(pre_dist)" these were not run lines ,I needs know dimension.

thank you.

**Comment by AkramMohammadi** [comment]
mr.Vitor
I used another data set from kaggle such as stream-video-games.csv, sample-data.csv have error "...has both Numeric and nominal values"
Are you can recommending from which data set type or you sent to used data set  for projects?
thank you.

**Comment by AkramMohammadi** [comment]
@
